### ISSUE TITLE
Updated Version

### ISSUE THREAD

**Issue by RoyiAvital** [2wayne/TeXstudioPlusPortable#1]
Hello,

Could you update this for the latest version of TeXStudio?
Also could it make compatible with the latest MiKTeX (Or update yours)?

Really appreciate your work on PortableApps.
I donated because of your work.

Thank You.

**Comment by 2wayne** [comment]
Updated and compatible with latest MiKTeX.
See: https://sourceforge.net/projects/mwayne/files/TeXstudioPlusPortable/

**Comment by RoyiAvital** [comment]
@2wayne , Any chance you add to this [TeXMaker](http://www.xm1math.net/texmaker/) as well?

It is a great piece of TeX Editor as well.

Thank You.

P. S.
You should have a donation address added.

**Comment by RoyiAvital** [comment]
@2wayne ,
Any comment on TeXMaker?

Thank You.
